// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: greeting.proto

package greetEng

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreetingEngClient is the client API for GreetingEng service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetingEngClient interface {
	SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type greetingEngClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetingEngClient(cc grpc.ClientConnInterface) GreetingEngClient {
	return &greetingEngClient{cc}
}

func (c *greetingEngClient) SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/greetEng.GreetingEng/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetingEngServer is the server API for GreetingEng service.
// All implementations must embed UnimplementedGreetingEngServer
// for forward compatibility
type GreetingEngServer interface {
	SayHello(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedGreetingEngServer()
}

// UnimplementedGreetingEngServer must be embedded to have forward compatible implementations.
type UnimplementedGreetingEngServer struct {
}

func (UnimplementedGreetingEngServer) SayHello(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetingEngServer) mustEmbedUnimplementedGreetingEngServer() {}

// UnsafeGreetingEngServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetingEngServer will
// result in compilation errors.
type UnsafeGreetingEngServer interface {
	mustEmbedUnimplementedGreetingEngServer()
}

func RegisterGreetingEngServer(s grpc.ServiceRegistrar, srv GreetingEngServer) {
	s.RegisterService(&GreetingEng_ServiceDesc, srv)
}

func _GreetingEng_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingEngServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetEng.GreetingEng/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingEngServer).SayHello(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// GreetingEng_ServiceDesc is the grpc.ServiceDesc for GreetingEng service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetingEng_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greetEng.GreetingEng",
	HandlerType: (*GreetingEngServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreetingEng_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeting.proto",
}
